name: VotemineReward
version: ${project.version}
api-version: "1.15"
main: com.votemine.votemineReward.VotemineReward
authors: [HOVOH]
website: votemine.com
commands:
  voteminereward:
    aliases: ['voteshop','vmr']